### ISSUE TITLE
IntelliJ Plugin not visible on Marketplace

### ISSUE THREAD

**Issue by michael-schnell** [ZenWave360/zdl-jvm#5]
I tried to install the IntelliJ plugin on IntelliJ IDEA 2023.3.2 (Ultimate) but the plugin is not displayed on the Marketplace 
(Same with Same with 2022.3.3 and 2022.2.5).

Looks like the version of the plugin is not compatible with those versions and therefore not visible.

Is there an updated version of the plugin available that supports more recent versions of IntelliJ?

**Comment by ivangsa** [comment]
Hi @michael-schnell 
the IntelliJ plugin is on it's very early stages that's why is hidden in the Marketplace, but you can install it through direct download.. 
It already provides useful functionality and we use it internally already, but it's not ready for prime-time 
thanks a lot for your interest...

**Comment by michael-schnell** [comment]
Can you provide a link? I didn't find a repository or download link for it.

**Comment by ivangsa** [comment]
https://www.zenwave360.io/plugin/

previously was at https://zenwave360.github.io/plugin/
